### ISSUE TITLE
Nepřeložené "rádio" hostess

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#112]
Nepřeložené hostess v restauraci Rudý Drak v Čínské čtvrti.
https://snag.gy/WTrPvk.jpg
https://snag.gy/59gCWH.jpg

**Comment by miracleflame** [comment]
Na rádio máme otvorené tikety #77 - #81

**Comment by miracleflame** [comment]
@soulcharmer prosím zreviduj:

"Hello? Hey, baby. No, I'm still at work. I don't know, why WOULD I want to rush home right away? . . .yeah? I do like that. What else? With a what?! [misunderstanding]Ohh. . .you're in the kitchen, yeah, they were on sale so I bought some. You do too like zucchini!"
"Haló? Čau, zlato. Ne, jsem stále v práci. Já nevím, proč bych MĚLA chtít pospíchat domů? . . .Jo? To se mi líbí. Co ještě? S čím?! [misunderstanding]Aha... ty jsi v kuchyni, jo, byli ve slevě, tak jsem jich zopár koupila. Ty máš přece taky rád cuketu!"

"Hey, Andrea. Uh-huh. What? No, he's not. . . no he's not! NO HE IS NOT! Hold on, Andrea, I've got another call. Hey, Serena, did you here about Joe and. . .yes he is. Yeah, he is! YES HE IS! I know, I was just on the phone with Andrea, and I was all, 'no, he's not!' YES HE IS!" 
"Čau, Andreo. A-hah. Cože? Ne, není. . . ne, není! NE, NENÍ! Počkej, Andreo, mám tu jiný hovor. Čau, Sereno, už jsi slyšela o Joeovi a... Ano, je. Ano, je! ANO? JE! Já vím, teď jsem volala s Andreou, a dělala jsem, jako že 'né, není!' ÁNO, JE!"

"Hey, Andrea. Uh-huh. What? The dark father returns? No, he's not. . . no he's not! NO HE IS NOT! Hold on, Andrea, I've got another call. Hey, Serena, did you here about. . .yes he is. Yeah, he is! YES HE IS! I know, I was just on the phone with Andrea, and I was all, 'no, he's not!' YES HE IS!" 
"Čau, Andreo. A-hah. Cože? Temný otec je na cestě zpět? Ne, není. . . ne, není! NE, NENÍ! Počkej, Andreo, mám tu jiný hovor. Čau, Sereno, už jsi slyšela o Joeovi a... Ano, je. Ano, je! ANO? JE! Já vím, teď jsem volala s Andreou, a dělala jsem, jako že 'né, není!' ÁNO, JE!"

"Heloo. Oh, hey, Andrea. Yeah, I'm still at work. No, not tonight, I have plans, sorry. So what are you going to do tonight? Huh? . . .Yeah, I know they're on sale, I picked some up. I'll call you later, okay, sweetie?" 
"Haloo. Čau, Andreo. Jo, pořád jsem v práci. Ne, dnes večer ne, mám plány, promiň. A copak dnes večer děláš ty? Ha? ... Jo, vím, že jsou ve slevě, zopár jsem si jich nakoupila. Zavolám ti pak, okej, zlato?" 

"Yeah? Oh, hi, Milla, what do you want? . . .I'm sorry, I've got plans, I can't cover your shift tomorrow. What's the emergency? Well. . . it's not like it was sudden, I mean, he's been on life support for a long time. Funerals are usually over by five. When did you cover my shift? But that was an emergency! It was a REALLY bad haircut, Milla. . .Fine, I'll do it. Goodbye." 
"Jo? Oh, ahoj, Millo, copak potřebuješ? ... Je mi líto, mám plány, nemůžu za tebe zítra zaskočit. Co neodkladnýho se děje? Dobrá... ne že by to bylo nečekaný, chci říct, že byl na přístrojích už dost dlouho. Pohřeby obvykle končí ještě před pátou. A kdy si ty zaskočila za mně? Ale to bylo opravdu neodkladný! Byl to VÁŽNE důležitý účes, Milla... Fajn, udělám to. Měj se." 

"Yeah? Oh, hi, Milla, I hate you. I hate you for so many reasons - I don't even know where to begin. I have no sympathy towards your tragedy at all, mostly because you're smarter and more attractive than me - oh, and you're a kiss ass. So what if you helped me out, I've been wishing you'd get hit by a car for weeks. Fine, I'll do it. Goodbye." 
"Jo? Oh, ahoj, Millo, nesnáším tě. Mám tolik důvodů tě nesnášet, že ani nevím, kde začít. Nemám pro tvé neštěstí nejmenší soucit, zejména proto, že jsi chytřejší a atraktivnější než já - jo a lezeš lidem do prdele. A co když jsi mi pomohla, už celé týdny si přeju, aby tě přejelo auto. Fajn, udělám to. Měj se."

**Comment by miracleflame** [comment]
speaker_name ??? fix #314 
d9503bf7347220755f50dfd91d90cf5697c8fbe0
