### ISSUE TITLE
Mandarin nepřeložené

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#117]
Mandarin v Čínské čtvrti má nepřeložené některé části v rohu nahoře:
https://snag.gy/ex1kZS.jpg
https://snag.gy/rfLsh6.jpg

**Comment by miracleflame** [comment]
@soulcharmer na revíziu

"Subject refuses to move to the next chamber." 
"Subjekt se odmíta přesunout to další místnosti."

"The walls are reinforced concrete, several feet thick - there's no other exit, believe me, it is my design." 
"Steny jsou z tvrzeného betonu, hrubé několik stop - není odsud jiná cesta, věř mi, ije to můj dizajn."

"Subject will not enter the next area. This may be due to a theoretical sixth sense, or perhaps it is simply afraid." 
"Subjekt nechce vstoupit do další místnosti. Může to být díky teoretickému šestému smyslu, a nebo se prostě bojí."

"Subject is uncooperative. . . this may be a side effect of its condition or a residual personality defect."
"Subjekt nespolupracuje... může  to být vedlejší efekt jeho současného stavu, nebo pozůstatek defektu osobnosti."

"If you cooperate, I will give you a dog for your good behavior. I find my subjects prefer dog blood over the rats I normally give them." 
"Pokud budeš spolupracovat, dostaneš psa za dobré chování. Zjistil jsem, že mé subjekty preferují psí krev před krysí, kterou jim běžne dávám."

**Comment by soulcharmer** [comment]
"The walls are reinforced concrete, several feet thick - there's no other exit, believe me, it is my design."
"Ty zdi jsou z půlmetrového železobetonu - žádný jiný východ tu není, věř mi, sám jsem to navrhoval."

"Subject will not enter the next area. This may be due to a theoretical sixth sense, or perhaps it is simply afraid."
"Subjekt nechce vstoupit do další místnosti. Možná je to díky teoretickému šestému smyslu a nebo se prostě bojí."

"Subject is uncooperative. . . this may be a side effect of its condition or a residual personality defect."
"Subjekt nespolupracuje... může to být vedlejší efekt jeho současného stavu nebo pozůstatek poruchy osobnosti."

"If you cooperate, I will give you a dog for your good behavior. I find my subjects prefer dog blood over the rats I normally give them."
"Pokud budeš spolupracovat, dostaneš za dobré chování psa. Zjistil jsem, že testovací osoby mají raději psí krev než krysí, kterou jim běžně dávám."
