### ISSUE TITLE
Konec za Kamarillu - nepřeložen

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#139]
Není přeloženo, co regent říká.
https://snag.gy/dtYcsG.jpg
https://snag.gy/O5z64b.jpg
https://snag.gy/k8PdpE.jpg

**Comment by miracleflame** [comment]
@soulcharmer na preklad... v unisex forme

"Well done, neonate. Your powers are considerable for one so young. You will be a great asset in the years to come, and the sarcpagus will reside safely in the hands of the Camarilla."

"I told you before that there are some powers in this world that are best left undisturbed. I don't know what lies in the sarcophagus, and I believe that it may be in our best interests not to find out. If these be the final nights of our existence, I do not rush to bring about Gehenna any sooner that it need come."

"Let the shadows of time cover this dark treasure, so that eventually it fades even from our memories. Some things are best forgotten, neonate...some things are best forgotten..."

**Comment by miracleflame** [comment]
Použil som existujúci preklad z DLG a neonate som preložil do unisex podoby "dítě".

**Comment by miracleflame** [comment]
Na základe postrehu z #45 som aplikoval obojpohlavné lipy.
@Honzixx prosím otestuj ten koniec, či tam bude ženská verzia "novicko" (až urobím konverzný dump).

**Comment by Honzixx** [comment]
testováno, mám tam mužskou verzi "novici"

**Comment by miracleflame** [comment]
Takže tento konkrétny prípad je údajne riadený cez sound\cinematic\la\chambers\camarilla_bip1/2.vcd a nevidím tam moc priestoru na obojpohlavné lipy.

Revert na unisex.
