### ISSUE TITLE
Mafia

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#327]
https://snag.gy/Efk2Yw.jpg
Mafia>Mafián

Otázka na, nejspíš na Wespa při plížení+neviditelnost(5), když vypáčím vedlejší dveře od mísnosti kde je Bruno Giovani, tak Bruno vyrazí přední dveře a začne mě hledat to je tak schválně, nebo je to chyba chtěl jsem zkusit se k němu připlížit zezadu a zabít ho.

**Comment by miracleflame** [comment]
A odreportujem Wespovi.

**Comment by miracleflame** [comment]
Wesp: Sadly this can't be done because there is nobody inside that room but Bruno himself, the other "clan members" are using his model too, because Troika obviously had no time to add more Giovanni models. Entering the room stealthingly would make that obvious!

Síce som nepochopil, čo presne tým chcel povedať, ale vyplýva z toho, že to nebude riešiť.

**Comment by maarten93** [comment]
Já jsem to pochopil kdyby se šlo proplizit místnosti 
Tak by hráč zjistil že se Bruno baví sám se sebou,  proto ten scrip
